---
title: "XaringanExtra CoderGirls Aarhus October"
author: "Elena Dudukina"
date: "10/4/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r metathis, echo=FALSE}
library(metathis)
meta() %>%
  meta_name("github-repo" = "evpatora/2020-10-10-nordic-data-coder-girls/") %>% 
  meta_social(
    title = "Using R and tidyverse for publically available Nordic data",
    description = paste(
      "Upload, wrangle data, make it tidy and create visually appealing ggplot2 graphics",
      "Presented at CoderGirls Aarhus meet-up by Elena Dudukina"
    ),
    url = "https://coder-girls-aarhus-october-2020.netlify.app/",
    og_type = "website",
    og_author = "Elena Dudukina",
    twitter_creator = "@evpatora",
    twitter_site = "@evpatora"
  )
```

```{r}
#' Screenshot Your Title Slide for Share Image
#'
#' Takes a screenshot of your title slide for sharing on Twitter
#' (and other social media sites).
#'
#' @param slides_rmd Your slides file
#' @param path Path to new share image
screenshot_share_image <- function(
  slides_rmd,
  path_image = "share-card.png"
) {
  if (!requireNamespace("webshot2", quietly = TRUE)) {
    stop(
      "`webshot2` is required: ", 
      'remotes::install_github("rstudio/webshot2")'
    )
  }
  
  webshot2::rmdshot(
    doc = slides_rmd,
    file = path_image,
    vheight = 600,
    vwidth = 600 * 191 / 100,
    rmd_args = list(
      output_options = list(
        nature = list(ratio = "191:100"),
        self_contained = TRUE
      )
    )
  )
  
  path_image
}
```

